image: tiangolo/docker-with-compose

stages:
  - develop
  - prod
develop:
  stage: develop
  before_script:
    - docker login registry.devacceso.com --username=docker -p=peladonerd
  only:
    - develop
  tags:
    - swarm-dev
  variables:
    ENVDEPLOY: staging
    PORTDOCKER: 80
    PORTSALIDA: 5060
    IMAGENAME: $CI_PROJECT_NAME
    DOCKER_STACK: $CI_PROJECT_NAME
    NODO: dev
    SUBDOMINIO: gescol
    DOMINIO: devacceso.com
  script:
    - export
    - docker-compose build
    - docker-compose push
    - docker stack deploy -c docker-compose.yml $DOCKER_STACK --with-registry-auth

prod:
  stage: prod
  before_script:
    - docker login registry.devacceso.com --username=docker -p=peladonerd
  only:
    - master
  tags:
    - swarm-prod2022
  variables:
    ENVDEPLOY: build #Depende del package.json (depende del desarrolador)
    PORTDOCKER: 80
    PORTSALIDA: 5060
    IMAGENAME: $CI_PROJECT_NAME
    DOCKER_STACK: $CI_PROJECT_NAME
    NODO: worker-prod
    SUBDOMINIO: gescol
    DOMINIO: devacceso.com

  script:
    - export
    - docker-compose build
    - docker-compose push
    - docker stack deploy -c docker-compose.yml $DOCKER_STACK --with-registry-auth
